// Mock salon data for testing approval system
const mockSalons = [
  {
    _id: '507f1f77bcf86cd799439011',
    salonName: 'Test Beauty Salon',
    ownerName: 'John Doe',
    email: 'test@beauty.com',
    phone: '9876543210',
    address: '123 Main Street',
    city: 'Dehradun',
    state: 'Uttarakhand',
    pincode: '248001',
    services: [
      { name: 'Haircut', price: 200 },
      { name: 'Facial', price: 500 }
    ],
    offers: ['10% off on first visit'],
    phoneVerified: true,
    gender: 'female',
    salonType: 'unisex',
    contactInfo: 'test@beauty.com',
    openingTime: '9:00 AM',
    closingTime: '8:00 PM',
    status: 'pending',
    isActive: false,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '507f1f77bcf86cd799439012',
    salonName: 'Test Spa Center',
    ownerName: 'Jane Smith',
    email: 'spa@test.com',
    phone: '9876543211',
    address: '456 Park Avenue',
    city: 'Dehradun',
    state: 'Uttarakhand',
    pincode: '248002',
    services: [
      { name: 'Massage', price: 1000 },
      { name: 'Steam Bath', price: 300 }
    ],
    offers: ['Free consultation'],
    phoneVerified: true,
    gender: 'male',
    salonType: 'male',
    contactInfo: 'spa@test.com',
    openingTime: '10:00 AM',
    closingTime: '9:00 PM',
    status: 'pending',
    isActive: false,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '507f1f77bcf86cd799439013',
    salonName: 'Test Unisex Salon',
    ownerName: 'Alex Johnson',
    email: 'unisex@salon.com',
    phone: '9876543212',
    address: '789 Fashion Street',
    city: 'Dehradun',
    state: 'Uttarakhand',
    pincode: '248003',
    services: [
      { name: 'Hair Styling', price: 300 },
      { name: 'Beard Grooming', price: 150 },
      { name: 'Facial', price: 400 }
    ],
    offers: ['20% off on first visit', 'Free consultation'],
    phoneVerified: true,
    gender: 'unisex',
    salonType: 'unisex',
    contactInfo: 'unisex@salon.com',
    openingTime: '8:00 AM',
    closingTime: '10:00 PM',
    status: 'pending',
    isActive: false,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '507f1f77bcf86cd799439014',
    salonName: 'NEW USER SALON - JUST REGISTERED',
    ownerName: 'New User',
    email: 'newuser@test.com',
    phone: '9876543213',
    address: '999 New Street',
    city: 'Dehradun',
    state: 'Uttarakhand',
    pincode: '248004',
    services: [
      { name: 'Haircut', price: 250 },
      { name: 'Makeup', price: 600 }
    ],
    offers: ['New salon discount'],
    phoneVerified: true,
    gender: 'female',
    salonType: 'female',
    contactInfo: 'newuser@test.com',
    openingTime: '9:00 AM',
    closingTime: '7:00 PM',
    status: 'pending',
    isActive: false,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '507f1f77bcf86cd799439015',
    salonName: 'Divine Salon',
    ownerName: 'Divine Owner',
    email: 'divine@salon.com',
    phone: '9876543214',
    address: '777 Divine Street',
    city: 'Dehradun',
    state: 'Uttarakhand',
    pincode: '248005',
    services: [
      { name: 'Hair Styling', price: 350 },
      { name: 'Makeup', price: 750 },
      { name: 'Nail Art', price: 200 }
    ],
    offers: ['Premium services', 'Member discounts'],
    phoneVerified: true,
    gender: 'female',
    salonType: 'female',
    contactInfo: 'divine@salon.com',
    openingTime: '10:00 AM',
    closingTime: '8:00 PM',
    status: 'pending',
    isActive: false,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

module.exports = { mockSalons };
